### ISSUE TITLE
refactor Image component

### ISSUE THREAD

**Issue by jagodakubicka** [WitchDevelops/cardboard-fort#13]

**Comment by WitchDevelops** [comment]
adding a comment so it's clear what this issue is about:

Next.js optimizes images by their native `<Image>` component. This component improves image loading times, supports lazy loading, placeholder images, responsiveness, etc. Overall it's a good thing to use. We are not using it (and we should, e.g. for the `<PetCardImage>`. We need a code refactor to implement this component.
https://nextjs.org/docs/pages/api-reference/components/image
